import streamlit as st
import PyPDF2
import base64

from auth import login
from detector import check_scam
from database import save_report

# ---------------- PAGE CONFIG ----------------
st.set_page_config(
    page_title="AI Scam Detector SaaS",
    layout="centered"
)

# ---------------- CUSTOM CSS ----------------
st.markdown("""
<style>

/* Main Background */
.stApp {
    background-color: #f8fafc;
}

/* Titles */
h1, h2, h3 {
    color: #0f172a;
    font-weight: bold;
}

/* Text */
p, label, div {
    color: #111827;
    font-size: 16px;
}

/* Buttons */
.stButton>button {
    background-color: #2563eb;
    color: white;
    border-radius: 10px;
    padding: 10px 18px;
    border: none;
    font-weight: bold;
}

.stButton>button:hover {
    background-color: #1d4ed8;
}

/* Cards */
.card {
    background-color: white;
    padding: 18px;
    border-radius: 14px;
    margin: 10px 0px;
    box-shadow: 0px 4px 15px rgba(0,0,0,0.08);
    color: #111827;
    font-size: 18px;
    font-weight: 500;
}

/* Result Card */
.result-card {
    background-color: #dbeafe;
    padding: 25px;
    border-radius: 15px;
    color: #1e3a8a;
    box-shadow: 0px 4px 15px rgba(0,0,0,0.1);
    margin-bottom: 20px;
}

/* File Upload */
[data-testid="stFileUploader"] {
    background-color: white;
    padding: 15px;
    border-radius: 12px;
    border: 1px solid #cbd5e1;
}

</style>
""", unsafe_allow_html=True)

# ---------------- SESSION STATE ----------------
if "logged_in" not in st.session_state:
    st.session_state["logged_in"] = False

if "user" not in st.session_state:
    st.session_state["user"] = ""

# ---------------- PDF EXTRACTION ----------------
def extract_pdf_text(file):

    text = ""

    try:
        pdf_reader = PyPDF2.PdfReader(file)

        for page in pdf_reader.pages:
            page_text = page.extract_text()

            if page_text:
                text += page_text

        return text.strip()

    except Exception as e:
        st.error(f"PDF Error: {e}")
        return ""

# ---------------- REPORT FUNCTION ----------------
def generate_report(result, score, keywords, level):

    return f"""
===== AI SCAM DETECTION REPORT =====

User: {st.session_state['user']}

Result: {result}

Risk Level: {level}

Scam Score: {round(score, 2)}%

Suspicious Keywords:
{', '.join(keywords) if keywords else 'None'}

Generated by AI Scam Detection SaaS
"""

# ---------------- DOWNLOAD REPORT ----------------
def create_download_link(report_text):

    b64 = base64.b64encode(report_text.encode()).decode()

    return f'''
    <a href="data:file/txt;base64,{b64}"
    download="scam_report.txt">
    📥 Download Report
    </a>
    '''

# ---------------- HIGHLIGHT TEXT ----------------
def highlight_text(text, keywords):

    highlighted = text

    for word in keywords:
        highlighted = highlighted.replace(
            word,
            f"🔴 {word} 🔴"
        )

    return highlighted

# ================= LOGIN PAGE =================
if not st.session_state["logged_in"]:

    st.markdown("""
    <h1 style='text-align:center;'>
    🔐 AI Scam Detection Login
    </h1>
    """, unsafe_allow_html=True)

    st.markdown("""
    <p style='text-align:center;color:gray;'>
    Login to continue
    </p>
    """, unsafe_allow_html=True)

    username = st.text_input("Username")

    # SHOW PASSWORD FIX
    show_password = st.checkbox("Show Password")

    if show_password:
        password = st.text_input("Password")
    else:
        password = st.text_input("Password", type="password")

    if st.button("Login"):

        if login(username, password):

            st.success("Login Successful ✅")

            st.session_state["logged_in"] = True
            st.session_state["user"] = username

            st.rerun()

        else:
            st.error("Invalid Credentials ❌")

    st.stop()

# ================= MAIN APP =================
st.markdown("""
<h1 style='text-align:center;'>
📄 Offer Letter Scam Detector
</h1>
""", unsafe_allow_html=True)

# ---------------- TOP BAR ----------------
col1, col2 = st.columns([8, 2])

with col1:
    st.write(f"👋 Welcome **{st.session_state['user']}**")

with col2:
    if st.button("🚪 Logout"):
        st.session_state.clear()
        st.rerun()

st.markdown("---")

# ---------------- FILE UPLOAD ----------------
text = ""

uploaded_file = st.file_uploader(
    "Upload Offer Letter (PDF or TXT)",
    type=["pdf", "txt"]
)

if uploaded_file is not None:

    if uploaded_file.type == "application/pdf":

        text = extract_pdf_text(uploaded_file)

        if text.strip() == "":
            st.warning("⚠ Unable to extract text from this PDF")

    else:
        text = str(uploaded_file.read(), "utf-8")

# ================= ANALYZE =================
if st.button("Analyze"):

    if text.strip() == "":
        st.warning("❌ Please upload a readable file")

    else:

        result, score, keywords, level = check_scam(text)

        # SAVE HISTORY
        save_report(
            st.session_state["user"],
            score,
            result
        )

        # ---------------- RESULT CARD ----------------
        st.markdown(f"""
        <div class='result-card'>

        <h2>{result}</h2>

        <p style='font-size:20px;font-weight:bold;'>
        Scam Score: {round(score,2)}%
        </p>

        </div>
        """, unsafe_allow_html=True)

        # ---------------- PROGRESS ----------------
        st.progress(int(score))

        # ---------------- DASHBOARD ----------------
        st.markdown("## 📊 Dashboard")

        col1, col2, col3 = st.columns(3)

        with col1:
            st.markdown(f"""
            <div class='card'>
            💰 <b>Risk Score</b><br><br>
            {int(score)}%
            </div>
            """, unsafe_allow_html=True)

        with col2:
            st.markdown(f"""
            <div class='card'>
            🔍 <b>Keywords Found</b><br><br>
            {len(keywords)}
            </div>
            """, unsafe_allow_html=True)

        with col3:
            st.markdown(f"""
            <div class='card'>
            📌 <b>Status</b><br><br>
            {level}
            </div>
            """, unsafe_allow_html=True)

        # ---------------- STATUS ----------------
        if level == "HIGH":
            st.error("🔴 HIGH RISK DETECTED")

        elif level == "MEDIUM":
            st.warning("🟡 MEDIUM RISK DETECTED")

        else:
            st.success("🟢 LOW RISK - Looks Safe")

        # ---------------- KEYWORDS ----------------
        if keywords:

            st.markdown("## 🔍 Suspicious Keywords")

            for k in keywords:
                st.markdown(f"- 🔴 {k}")

        # ---------------- HIGHLIGHTED CONTENT ----------------
        st.markdown("## 🔎 Highlighted Content")

        st.write(highlight_text(text, keywords))

        # ---------------- DOWNLOAD REPORT ----------------
        report = generate_report(
            result,
            score,
            keywords,
            level
        )

        st.markdown("## 📥 Download Report")

        st.markdown(
            create_download_link(report),
            unsafe_allow_html=True
        )

# ================= HISTORY =================
st.markdown("---")

if st.button("📊 Show My Scan History"):

    import sqlite3

    conn = sqlite3.connect("scam.db")

    c = conn.cursor()

    c.execute(
        "SELECT * FROM reports WHERE user=?",
        (st.session_state["user"],)
    )

    data = c.fetchall()

    st.markdown("## 📜 Your History")

    if len(data) == 0:
        st.info("No history found")

    else:

        for row in data:

            st.markdown(f"""
            <div class='card'>
            {row}
            </div>
            """, unsafe_allow_html=True)